---
- name: Hardening del Wazuh Manager (VM2)
  hosts: wazuh_manager
  become: yes
  tasks:
    - name: 1. Configurar politica de contraseñas (pam_pwquality)
      ansible.builtin.lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*minlen\s*='
        line: 'minlen = 12'

    - name: 2. Deshabilitar servicios innecesarios
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - postfix
        - avahi-daemon
        - cockpit
      failed_when: false

    - name: 3. Asegurar que firewalld este iniciado
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: 4. Permitir puertos legitimos del Wazuh Manager y Dashboard
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 22/tcp
        - 443/tcp
        - 1514/tcp
        - 1515/tcp
        - 9200/tcp

    - name: 5. Hardening de SSH (Bloquear root de forma directa)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Reiniciar SSH

  handlers:
    - name: Reiniciar SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
